export const RECEIVE_SWARM_NODES = 'RECEIVE_SWARM_NODES';
export const RECEIVE_TASKS = 'RECEIVE_TASKS';
export const SHOW_MODAL = 'SHOW_MODAL';
export const HIDE_MODAL = 'HIDE_MODAL';
export const SOCKET_IO_RECEIVE = 'SOCKET_IO_RECEIVE';